
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 5;
  public static final int LCBR = 11;
  public static final int LTE = 23;
  public static final int LPAREN = 6;
  public static final int SEMI = 13;
  public static final int CONTINUE = 29;
  public static final int INT = 42;
  public static final int MINUS = 3;
  public static final int STATIC = 38;
  public static final int RPAREN = 7;
  public static final int LT = 22;
  public static final int COMMA = 14;
  public static final int CLASS = 27;
  public static final int PLUS = 2;
  public static final int ASSIGN = 16;
  public static final int IF = 33;
  public static final int THIS = 39;
  public static final int DOT = 15;
  public static final int ID = 32;
  public static final int EOF = 0;
  public static final int RETURN = 37;
  public static final int RCBR = 12;
  public static final int LB = 9;
  public static final int LAND = 21;
  public static final int EQUAL = 17;
  public static final int TRUE = 44;
  public static final int NEW = 35;
  public static final int error = 1;
  public static final int RB = 10;
  public static final int LOR = 20;
  public static final int NULL = 36;
  public static final int NUMBER = 45;
  public static final int MOD = 8;
  public static final int BREAK = 26;
  public static final int VOID = 40;
  public static final int GTE = 25;
  public static final int TIMES = 4;
  public static final int ELSE = 31;
  public static final int WHILE = 41;
  public static final int NEQUAL = 18;
  public static final int CLASS_ID = 28;
  public static final int EXTENDS = 30;
  public static final int LNEG = 19;
  public static final int FALSE = 43;
  public static final int GT = 24;
  public static final int LENGTH = 34;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "LPAREN",
  "RPAREN",
  "MOD",
  "LB",
  "RB",
  "LCBR",
  "RCBR",
  "SEMI",
  "COMMA",
  "DOT",
  "ASSIGN",
  "EQUAL",
  "NEQUAL",
  "LNEG",
  "LOR",
  "LAND",
  "LT",
  "LTE",
  "GT",
  "GTE",
  "BREAK",
  "CLASS",
  "CLASS_ID",
  "CONTINUE",
  "EXTENDS",
  "ELSE",
  "ID",
  "IF",
  "LENGTH",
  "NEW",
  "NULL",
  "RETURN",
  "STATIC",
  "THIS",
  "VOID",
  "WHILE",
  "INT",
  "FALSE",
  "TRUE",
  "NUMBER"
  };
}

